-- ============================================================
-- FASE 5 — Seed de tabla CIE-10 (códigos más frecuentes en clínicas)
-- ============================================================
INSERT IGNORE INTO cie10 (codigo, descripcion, categoria) VALUES
-- Enfermedades infecciosas y parasitarias (A00–B99)
('A00.0','Cólera por Vibrio cholerae','Infecciosas'),
('A01.0','Fiebre tifoidea','Infecciosas'),
('A02.0','Enteritis por Salmonella','Infecciosas'),
('A06.0','Disentería amebiana aguda','Infecciosas'),
('A09',  'Gastroenteritis y colitis de origen infeccioso NE','Infecciosas'),
('A15.0','Tuberculosis pulmonar con confirmación por cultivo','Infecciosas'),
('A36.0','Difteria faríngea','Infecciosas'),
('A37.0','Tos ferina por Bordetella pertussis','Infecciosas'),
('A39.0','Meningitis meningocócica','Infecciosas'),
('A50.0','Sífilis congénita precoz sintomática','Infecciosas'),
('A63.0','Condilomas acuminados','Infecciosas'),
('A90', 'Dengue','Infecciosas'),
('A91', 'Dengue hemorrágico','Infecciosas'),
('B00.1','Dermatitis vesicular herpética','Infecciosas'),
('B01.9','Varicela sin complicaciones','Infecciosas'),
('B02.9','Herpes zóster sin complicaciones','Infecciosas'),
('B06.9','Rubéola sin complicaciones','Infecciosas'),
('B19.9','Hepatitis viral no especificada','Infecciosas'),
('B20',  'Enfermedad por VIH que resulta en enfermedades infecciosas','Infecciosas'),
('B34.9','Infección viral NE','Infecciosas'),
('B35.1','Tiña de las uñas (Onicomicosis)','Infecciosas'),
('B35.4','Tiña del cuerpo','Infecciosas'),
('B35.6','Tiña del pie (Pie de atleta)','Infecciosas'),
('B37.0','Estomatitis candidiásica','Infecciosas'),
('B37.3','Candidiasis de la vulva y vagina','Infecciosas'),
-- Neoplasias (C00–D49)
('C00.9','Neoplasia maligna del labio NE','Neoplasias'),
('C18.9','Neoplasia maligna del colon NE','Neoplasias'),
('C20',  'Neoplasia maligna del recto','Neoplasias'),
('C34.9','Neoplasia maligna del bronquio y pulmón NE','Neoplasias'),
('C50.9','Neoplasia maligna de la mama NE','Neoplasias'),
('C53.9','Neoplasia maligna del cuello del útero NE','Neoplasias'),
('C61',  'Neoplasia maligna de la próstata','Neoplasias'),
('C73',  'Neoplasia maligna de la glándula tiroides','Neoplasias'),
-- Enfermedades de la sangre (D50–D89)
('D50.0','Anemia por deficiencia de hierro (ferropénica)','Hemato'),
('D50.9','Anemia por deficiencia de hierro NE','Hemato'),
('D64.9','Anemia NE','Hemato'),
('D69.3','Púrpura trombocitopénica idiopática','Hemato'),
-- Enfermedades endocrinas (E00–E90)
('E03.9','Hipotiroidismo NE','Endocrino'),
('E05.0','Hipertiroidismo con bocio difuso (tóxico)','Endocrino'),
('E10.9','Diabetes mellitus tipo 1 sin complicaciones','Endocrino'),
('E11.0','Diabetes mellitus tipo 2 con coma','Endocrino'),
('E11.3','Diabetes mellitus tipo 2 con complicaciones oftálmicas','Endocrino'),
('E11.5','Diabetes mellitus tipo 2 con complicaciones de la circulación periférica','Endocrino'),
('E11.9','Diabetes mellitus tipo 2 sin complicaciones','Endocrino'),
('E14.9','Diabetes mellitus NE sin complicaciones','Endocrino'),
('E23.2','Diabetes insípida','Endocrino'),
('E28.2','Síndrome de ovario poliquístico','Endocrino'),
('E66.0','Obesidad por exceso de calorías','Endocrino'),
('E78.0','Hipercolesterolemia pura','Endocrino'),
('E78.1','Hipertrigliceridemia pura','Endocrino'),
('E78.5','Hiperlipidemia NE','Endocrino'),
('E83.5','Trastornos del metabolismo del calcio','Endocrino'),
-- Trastornos mentales (F00–F99)
('F06.3','Trastornos del afecto orgánicos','Mental'),
('F10.0','Transtornos mentales por uso de alcohol (intoxicación aguda)','Mental'),
('F20.0','Esquizofrenia paranoide','Mental'),
('F31.0','Trastorno afectivo bipolar, episodio hipomaníaco','Mental'),
('F32.0','Episodio depresivo leve','Mental'),
('F32.1','Episodio depresivo moderado','Mental'),
('F32.9','Episodio depresivo NE','Mental'),
('F33.0','Trastorno depresivo recurrente, episodio actual leve','Mental'),
('F40.0','Agorafobia','Mental'),
('F40.1','Fobias sociales','Mental'),
('F40.2','Fobias específicas','Mental'),
('F41.0','Trastorno de pánico','Mental'),
('F41.1','Trastorno de ansiedad generalizada','Mental'),
('F41.9','Trastorno de ansiedad NE','Mental'),
('F43.0','Reacción al estrés agudo','Mental'),
('F43.1','Trastorno de estrés postraumático (TEPT)','Mental'),
('F44.0','Amnesia disociativa','Mental'),
('F45.0','Trastorno de somatización','Mental'),
('F51.0','Insomnio no orgánico','Mental'),
('F60.3','Trastorno límite de la personalidad','Mental'),
('F84.0','Autismo infantil','Mental'),
('F90.0','Trastorno de la actividad y la atención (TDAH)','Mental'),
('F98.0','Enuresis no orgánica','Mental'),
-- Sistema nervioso (G00–G99)
('G03.9','Meningitis NE','Neurología'),
('G20',  'Enfermedad de Parkinson','Neurología'),
('G30.0','Enfermedad de Alzheimer de inicio temprano','Neurología'),
('G30.9','Enfermedad de Alzheimer NE','Neurología'),
('G35',  'Esclerosis múltiple','Neurología'),
('G40.0','Epilepsia localizada idiopática sin convulsiones generalizadas','Neurología'),
('G40.9','Epilepsia NE','Neurología'),
('G43.0','Migraña sin aura (migraña común)','Neurología'),
('G43.1','Migraña con aura (migraña clásica)','Neurología'),
('G43.9','Migraña NE','Neurología'),
('G44.2','Cefalea tensional','Neurología'),
('G44.9','Síndrome de cefalea NE','Neurología'),
('G45.9','Crisis isquémica transitoria NE','Neurología'),
('G51.0','Parálisis de Bell (parálisis facial periférica)','Neurología'),
('G54.2','Lesión de las raíces cervicales NE','Neurología'),
('G54.4','Lesión de las raíces lumbosacras NE (Lumbociática)','Neurología'),
('G62.9','Polineuropatía NE','Neurología'),
('G63.2','Polineuropatía diabética','Neurología'),
-- Ojo y anexos (H00–H59)
('H00.0','Orzuelo y otras inflamaciones del párpado','Oftalmología'),
('H10.1','Conjuntivitis atópica aguda','Oftalmología'),
('H10.9','Conjuntivitis NE','Oftalmología'),
('H25.9','Catarata senil NE','Oftalmología'),
('H26.9','Catarata NE','Oftalmología'),
('H35.0','Retinopatía del fondo de ojo NE','Oftalmología'),
('H36.0','Retinopatía diabética','Oftalmología'),
('H40.1','Glaucoma primario de ángulo abierto','Oftalmología'),
('H52.0','Hipermetropía','Oftalmología'),
('H52.1','Miopía','Oftalmología'),
('H52.2','Astigmatismo','Oftalmología'),
('H52.4','Presbicia','Oftalmología'),
-- Oído (H60–H95)
('H61.2','Cerumen impactado','Otología'),
('H65.0','Otitis media aguda serosa','Otología'),
('H66.0','Otitis media aguda supurada','Otología'),
('H66.9','Otitis media NE','Otología'),
('H72.9','Perforación del tímpano NE','Otología'),
('H81.0','Síndrome de Ménière','Otología'),
('H81.1','Vértigo paroxístico benigno de posición','Otología'),
('H83.3','Ruidos en el oído (Tinnitus)','Otología'),
-- Aparato circulatorio (I00–I99)
('I10',  'Hipertensión esencial (primaria)','Cardiovascular'),
('I11.0','Cardiopatía hipertensiva con insuficiencia cardíaca','Cardiovascular'),
('I20.0','Angina de pecho inestable','Cardiovascular'),
('I20.9','Angina de pecho NE','Cardiovascular'),
('I21.0','Infarto agudo de miocardio de la pared anterior','Cardiovascular'),
('I21.9','Infarto agudo de miocardio NE','Cardiovascular'),
('I25.1','Cardiopatía aterosclerótica con angina de pecho','Cardiovascular'),
('I25.9','Cardiopatía isquémica crónica NE','Cardiovascular'),
('I34.0','Insuficiencia mitral','Cardiovascular'),
('I35.0','Estenosis aórtica','Cardiovascular'),
('I42.0','Miocardiopatía dilatada','Cardiovascular'),
('I48',  'Fibrilación y aleteo auricular','Cardiovascular'),
('I49.9','Arritmia cardíaca NE','Cardiovascular'),
('I50.0','Insuficiencia cardíaca congestiva','Cardiovascular'),
('I50.9','Insuficiencia cardíaca NE','Cardiovascular'),
('I63.9','Infarto cerebral NE (ACV isquémico)','Cardiovascular'),
('I64',  'Accidente vascular encefálico NE (ACV)','Cardiovascular'),
('I69.3','Secuelas de infarto cerebral','Cardiovascular'),
('I70.0','Aterosclerosis de la aorta','Cardiovascular'),
('I82.9','Trombosis venosa NE','Cardiovascular'),
('I83.9','Várices de los miembros inferiores NE','Cardiovascular'),
('I87.2','Insuficiencia venosa (crónica) (periférica)','Cardiovascular'),
-- Aparato respiratorio (J00–J99)
('J00',  'Rinofaringitis aguda (resfriado común)','Respiratorio'),
('J01.0','Sinusitis maxilar aguda','Respiratorio'),
('J01.9','Sinusitis aguda NE','Respiratorio'),
('J02.0','Faringitis estreptocócica','Respiratorio'),
('J02.9','Faringitis aguda NE','Respiratorio'),
('J03.0','Amigdalitis estreptocócica','Respiratorio'),
('J03.9','Amigdalitis aguda NE','Respiratorio'),
('J04.0','Laringitis aguda','Respiratorio'),
('J06.0','Laringofaringitis aguda','Respiratorio'),
('J06.9','Infección aguda de las vías respiratorias superiores NE','Respiratorio'),
('J11.1','Gripe con otras manifestaciones respiratorias (virus no identificado)','Respiratorio'),
('J18.9','Neumonía NE','Respiratorio'),
('J20.9','Bronquitis aguda NE','Respiratorio'),
('J30.1','Rinitis alérgica debida a polen','Respiratorio'),
('J30.4','Rinitis alérgica NE','Respiratorio'),
('J32.0','Sinusitis maxilar crónica','Respiratorio'),
('J32.9','Sinusitis crónica NE','Respiratorio'),
('J35.0','Amigdalitis crónica','Respiratorio'),
('J35.3','Hipertrofia de las amígdalas con hipertrofia de las adenoides','Respiratorio'),
('J37.0','Laringitis crónica','Respiratorio'),
('J40',  'Bronquitis NE, aguda o crónica','Respiratorio'),
('J42',  'Bronquitis crónica no especificada','Respiratorio'),
('J44.1','EPOC con exacerbación aguda','Respiratorio'),
('J44.9','EPOC NE','Respiratorio'),
('J45.0','Asma predominantemente alérgica','Respiratorio'),
('J45.1','Asma no alérgica','Respiratorio'),
('J45.9','Asma NE','Respiratorio'),
('J46',  'Estado de mal asmático','Respiratorio'),
-- Aparato digestivo (K00–K93)
('K00.6','Alteraciones en la erupción de los dientes','Digestivo'),
('K02.0','Caries limitada al esmalte','Digestivo'),
('K04.0','Pulpitis','Digestivo'),
('K08.2','Pérdida de dientes por traumatismo','Digestivo'),
('K12.0','Aftas orales recurrentes','Digestivo'),
('K21.0','Enfermedad por reflujo gastroesofágico con esofagitis','Digestivo'),
('K21.9','Enfermedad por reflujo gastroesofágico sin esofagitis','Digestivo'),
('K25.0','Úlcera gástrica aguda con hemorragia','Digestivo'),
('K25.9','Úlcera gástrica NE','Digestivo'),
('K26.0','Úlcera duodenal aguda con hemorragia','Digestivo'),
('K26.9','Úlcera duodenal NE','Digestivo'),
('K29.5','Gastritis crónica NE','Digestivo'),
('K30',  'Dispepsia','Digestivo'),
('K35.9','Apendicitis aguda NE','Digestivo'),
('K37',  'Apendicitis NE','Digestivo'),
('K40.9','Hernia inguinal NE sin obstrucción ni gangrena','Digestivo'),
('K43.9','Hernia ventral NE sin obstrucción ni gangrena','Digestivo'),
('K52.9','Gastroenteritis y colitis no infecciosa NE','Digestivo'),
('K57.3','Enfermedad diverticular del intestino grueso sin perforación','Digestivo'),
('K58.0','Síndrome de intestino irritable con diarrea','Digestivo'),
('K58.9','Síndrome de intestino irritable NE','Digestivo'),
('K59.0','Estreñimiento','Digestivo'),
('K60.2','Fistula anal','Digestivo'),
('K61.0','Absceso anal','Digestivo'),
('K62.3','Sangrado del recto','Digestivo'),
('K64.9','Hemorroides NE','Digestivo'),
('K70.0','Hígado graso alcohólico','Digestivo'),
('K72.9','Insuficiencia hepática NE','Digestivo'),
('K73.9','Hepatitis crónica NE','Digestivo'),
('K74.6','Otra cirrosis hepática y la no especificada','Digestivo'),
('K76.0','Hígado graso no clasificado en otra parte (HGNA)','Digestivo'),
('K80.0','Colelitiasis con colecistitis aguda','Digestivo'),
('K80.2','Colelitiasis sin colecistitis','Digestivo'),
('K85.9','Pancreatitis aguda NE','Digestivo'),
('K86.1','Otras pancreatitis crónicas','Digestivo'),
-- Aparato urinario (N00–N99)
('N00.9','Síndrome nefrítico agudo NE','Nefrología'),
('N17.9','Lesión renal aguda NE','Nefrología'),
('N18.3','Enfermedad renal crónica etapa 3','Nefrología'),
('N18.9','Enfermedad renal crónica NE','Nefrología'),
('N20.0','Cálculo del riñón (nefrolitiasis)','Urología'),
('N20.1','Cálculo del uréter (ureterolitiasis)','Urología'),
('N23',  'Cólico renal NE','Urología'),
('N30.0','Cistitis aguda','Urología'),
('N39.0','Infección de vías urinarias de sitio no especificado','Urología'),
('N40',  'Hiperplasia de la próstata','Urología'),
('N41.0','Prostatitis aguda','Urología'),
('N41.1','Prostatitis crónica','Urología'),
('N45.9','Orquitis y epididimitis NE','Urología'),
('N48.1','Balanitis','Urología'),
('N52.9','Disfunción eréctil NE','Urología'),
('N70.0','Salpingitis aguda y ooforitis','Ginecología'),
('N71.0','Enfermedad inflamatoria aguda del útero','Ginecología'),
('N76.0','Vaginitis aguda','Ginecología'),
('N89.5','Estenosis e imperforación de la vagina NE','Ginecología'),
('N91.0','Amenorrea primaria','Ginecología'),
('N91.2','Amenorrea NE','Ginecología'),
('N92.0','Menstruación excesiva y frecuente con ciclo regular','Ginecología'),
('N92.6','Menstruación irregular NE','Ginecología'),
('N94.3','Síndrome premenstrual (SPM)','Ginecología'),
('N94.6','Dismenorrea NE','Ginecología'),
('N95.1','Menopausia y climaterio femenino','Ginecología'),
-- Embarazo, parto y puerperio (O00–O99)
('O00.0','Embarazo ectópico abdominal','Obstetricia'),
('O00.1','Embarazo tubárico','Obstetricia'),
('O03.9','Aborto espontáneo NE incompleto sin complicaciones','Obstetricia'),
('O10.0','Hipertensión esencial preexistente complicando el embarazo','Obstetricia'),
('O12.0','Edema gestacional','Obstetricia'),
('O14.0','Preeclampsia moderada','Obstetricia'),
('O14.1','Preeclampsia severa','Obstetricia'),
('O15.0','Eclampsia en el embarazo','Obstetricia'),
('O24.4','Diabetes mellitus que surge durante el embarazo (gestacional)','Obstetricia'),
('O42.9','Rotura prematura de membranas NE','Obstetricia'),
('O60.0','Parto pretérmino sin trabajo de parto','Obstetricia'),
('O80',  'Parto único espontáneo, presentación cefálica de vértice','Obstetricia'),
-- Piel y tejido subcutáneo (L00–L99)
('L01.0','Impétigo no ampolloso','Dermatología'),
('L02.9','Absceso cutáneo, forúnculo y carbunco NE','Dermatología'),
('L03.9','Celulitis NE','Dermatología'),
('L08.0','Pioderma','Dermatología'),
('L20.9','Dermatitis atópica NE','Dermatología'),
('L23.9','Dermatitis alérgica de contacto NE','Dermatología'),
('L25.9','Dermatitis de contacto NE','Dermatología'),
('L29.9','Prurito NE','Dermatología'),
('L30.0','Dermatitis numular','Dermatología'),
('L30.9','Dermatitis NE','Dermatología'),
('L40.0','Psoriasis en placas','Dermatología'),
('L50.0','Urticaria alérgica','Dermatología'),
('L50.9','Urticaria NE','Dermatología'),
('L52',  'Eritema nudoso','Dermatología'),
('L57.0','Queratosis actínica','Dermatología'),
('L60.0','Uña encarnada','Dermatología'),
('L70.0','Acné vulgaris','Dermatología'),
('L71.0','Dermatitis periorbitaria','Dermatología'),
('L72.1','Tricocilindroma (Quiste pilosebáceo)','Dermatología'),
('L80',  'Vitíligo','Dermatología'),
('L81.0','Hiperpigmentación postinflamatoria','Dermatología'),
('L90.0','Liquen escleroso y atrófico','Dermatología'),
-- Sistema musculoesquelético (M00–M99)
('M05.9','Artritis reumatoide seropositiva NE','Reumatología'),
('M06.9','Artritis reumatoide NE','Reumatología'),
('M10.0','Gota idiopática','Reumatología'),
('M15.0','Poliartrosis primaria','Reumatología'),
('M16.9','Coxartrosis NE (Artrosis de cadera)','Reumatología'),
('M17.1','Gonartrosis primaria bilateral (Artrosis de rodilla)','Reumatología'),
('M17.9','Gonartrosis NE','Reumatología'),
('M19.9','Artrosis NE','Reumatología'),
('M25.5','Dolor articular','Reumatología'),
('M32.9','Lupus eritematoso sistémico NE','Reumatología'),
('M41.9','Escoliosis NE','Traumatología'),
('M47.8','Espondiloartrosis NE','Traumatología'),
('M48.0','Estenosis del conducto vertebral','Traumatología'),
('M50.1','Enfermedad del disco intervertebral cervical con radiculopatía','Traumatología'),
('M51.1','Deformidades de los discos intervertebrales lumbares con radiculopatía','Traumatología'),
('M54.2','Cervicalgia','Traumatología'),
('M54.4','Lumbago con ciática','Traumatología'),
('M54.5','Lumbago NE (Lumbalgia)','Traumatología'),
('M54.9','Dorsalgia NE','Traumatología'),
('M65.3','Dedo en gatillo (Tenosinovitis estenosante)','Traumatología'),
('M72.2','Fibromatosis de la fascia plantar (Fascitis plantar)','Traumatología'),
('M75.1','Síndrome del manguito rotatorio','Traumatología'),
('M79.3','Paniculitis','Reumatología'),
('M79.7','Fibromialgia','Reumatología'),
('M80.9','Osteoporosis con fractura patológica NE','Traumatología'),
('M81.9','Osteoporosis NE','Traumatología'),
-- Traumatismos (S00–S99)
('S01.0','Herida del cuero cabelludo','Traumatismo'),
('S09.9','Traumatismo de la cabeza NE','Traumatismo'),
('S13.1','Luxación de articulación cervical','Traumatismo'),
('S20.0','Contusión del seno','Traumatismo'),
('S30.0','Contusión del dorso, región lumbar y pelvis','Traumatismo'),
('S52.5','Fractura del extremo distal del radio','Traumatismo'),
('S60.8','Traumatismo superficial de otra parte de la muñeca y mano','Traumatismo'),
('S72.0','Fractura del cuello del fémur','Traumatismo'),
('S82.0','Fractura de la rótula','Traumatismo'),
('S82.6','Fractura del peroné','Traumatismo'),
('S82.9','Fractura de la pierna NE','Traumatismo'),
('S93.0','Luxación de la articulación del tobillo','Traumatismo'),
('S93.4','Esguince y torcedura del tobillo','Traumatismo'),
-- Síntomas y signos generales (R00–R99)
('R00.0','Taquicardia NE','Síntomas'),
('R00.1','Bradicardia NE','Síntomas'),
('R00.8','Otras anormalidades del latido cardíaco y las NE','Síntomas'),
('R04.2','Hemoptisis','Síntomas'),
('R05',  'Tos','Síntomas'),
('R06.0','Disnea','Síntomas'),
('R06.4','Hiperventilación','Síntomas'),
('R07.0','Dolor de garganta','Síntomas'),
('R07.4','Dolor en el pecho NE','Síntomas'),
('R09.0','Asfixia','Síntomas'),
('R10.0','Abdomen agudo','Síntomas'),
('R10.4','Otros dolores abdominales y los no especificados','Síntomas'),
('R11',  'Náuseas y vómitos','Síntomas'),
('R12',  'Pirosis','Síntomas'),
('R13',  'Disfagia','Síntomas'),
('R14',  'Flatulencia y trastornos afines','Síntomas'),
('R19.4','Cambios en el hábito intestinal','Síntomas'),
('R20.2','Parestesia en la piel','Síntomas'),
('R25.2','Calambres y espasmos musculares','Síntomas'),
('R41.0','Desorientación NE','Síntomas'),
('R41.3','Otras amnesias','Síntomas'),
('R42',  'Mareo y vértigo','Síntomas'),
('R50.9','Fiebre NE','Síntomas'),
('R51',  'Cefalea','Síntomas'),
('R52.9','Dolor NE','Síntomas'),
('R53',  'Malestar y fatiga (Astenia)','Síntomas'),
('R55',  'Síncope y colapso','Síntomas'),
('R56.0','Convulsiones febriles','Síntomas'),
('R60.0','Edema localizado','Síntomas'),
('R60.9','Edema NE','Síntomas'),
('R63.0','Anorexia','Síntomas'),
('R63.4','Pérdida de peso anormal','Síntomas'),
('R68.0','Hipotermia no clasificada en otra parte','Síntomas'),
('R73.0','Glucosa en sangre anormal (Hiperglucemia NE)','Síntomas'),
('R79.0','Nivel anormal de elementos minerales en la sangre','Síntomas'),
-- Causas externas (Z00–Z99)
('Z00.0','Chequeo médico general','Preventivo'),
('Z00.1','Control de niño sano','Preventivo'),
('Z03.9','Observación médica por sospecha de enfermedad NE','Preventivo'),
('Z11.4','Tamizaje de VIH','Preventivo'),
('Z12.0','Tamizaje neoplasia estómago','Preventivo'),
('Z12.5','Tamizaje neoplasia de próstata','Preventivo'),
('Z23',  'Vacunación contra enfermedades bacterianas únicas','Preventivo'),
('Z30.0','Consejo y asesoramiento general sobre anticoncepción','Preventivo'),
('Z51.5','Cuidados paliativos','Preventivo'),
('Z71.1','Persona que consulta para aclarar un problema de salud','Preventivo'),
('Z76.2','Control de salud de recién nacido','Preventivo');
